import './globals.css'
import { Open_Sans } from 'next/font/google'
import { Navbar } from '@/components/Navbar/navbar'

const openSans = Open_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={`${openSans.className} bg-gray px-4 md:px-16`}>
          <Navbar />
        <main className="mt-24 md:mt-36">{children}</main> 
      </body>
    </html>
  )
}
