# fly.toml app configuration file generated for rough-sun-5423 on 2023-07-10T15:15:40-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-sun-5423"
primary_region = "gig"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
