# fly.toml app configuration file generated for quiet-cloud-5669 on 2023-07-10T19:59:29-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "quiet-cloud-5669"
primary_region = "gru"

[http_service]
  internal_port = 1337
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
